---
title: "Statistical Simulation and Inferential Data Analysis"
subtitle: "Inferential Statistics: Course Project"
author: "John Snyder"
date: "August 26, 2018"
output: 
    html_document:
      number_sections: yes
---

# Overview

# Simulations

```{r}
library(ggplot2)

lambda <- 0.2
n <- 40
m <- 1000

set.seed(2018)
expSamples <- rexp(n*m, lambda)
expMatrix <- matrix(expSamples, ncol=n, nrow=m)
```

```{r}
ggplot(data.frame(exp=expSamples), aes(x=exp)) +
    geom_histogram(color="black", bins=50, aes(y=..density..)) +
    stat_function(fun=dexp,
                  color="red",
                  size=2,
                  args=list(rate=lambda))+
    labs(y="Probability Density",
         x="Observed Value",
         title="Exponential Distribution Simulated Sample and PDF")
```

# Sample vs. Theoretical Mean

Code for the graphs below is based on the code provided in [a StackExchange question](https://stackoverflow.com/questions/29182228/plotting-normal-curve-over-histogram-using-ggplot2-code-produces-straight-line)
```{r}
# Calculate the means of the 1000 Samples
expMeans <- apply(expMatrix, 1, mean)

# Plot the distribution of means, along with the theoretical mean for
# the exponential distribution, the measured mean, and the PDF for 
# a normal distribution with a mean equal to the theoretical mean and
# a standard deviation equal to our sample standard deviation.
ggplot(data.frame(means = expMeans), aes(x=means)) +
    geom_histogram(color = "black", bins=50, aes(y=..density..)) +
    stat_function(fun=dnorm, 
                  color="red",
                  size=2,
                  args = list(mean=1/lambda, 
                              sd=sd(expMeans))) +
    geom_vline(xintercept = 1/lambda, color="red", size=2)+
    geom_vline(xintercept = mean(expMeans), color="blue", size=2) +
    labs(y="Probability Density",
         x="Sample Mean (n=40)",
         title="Sample of 1000 Means From the Exponential Distribution")
```

# Sample vs. Theoretical Variance

```{r}
expSDs <- apply(expMatrix, 1, sd)

ggplot(data.frame(sd = expSDs), aes(x=sd)) +
    geom_histogram(color = "black", bins=50, aes(y=..density..)) +
    stat_function(fun=dnorm, 
                  color="red",
                  size=2,
                  args = list(mean=1/lambda, 
                              sd=sd(expSDs))) +
    geom_vline(xintercept = 1/lambda, color="red", size=2)+
    geom_vline(xintercept = mean(expSDs), color="blue", size=2) +
    labs(y="Probability Density",
         x="Sample Standard Deviation (n=40)",
         title="Sample of 1000 Standard Deviations From the Exponential Distribution")
```